# Weather prediction
- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - minutely_summary
    - precip_intensity
    - precip_probability
    - temperature
    - dew_point
    - wind_speed
    - cloud_cover
    - humidity
    - pressure
    - visibility

- platform: mqtt
  name: "Raw temperature"
  state_topic: "sonoff/dht11/tele/SENSOR"
  value_template: "{{ value_json['DHT11']['Temperature'] }}"
  unit_of_measurement: "°C"
  icon: mdi:thermometer

- platform: mqtt
  name: "Raw humidity"
  state_topic: "sonoff/dht11/tele/SENSOR"
  value_template: "{{ value_json['DHT11']['Humidity'] }}"
  unit_of_measurement: "%"
  icon: mdi:water-percent

- platform: filter
  name: "Temperature"
  entity_id: sensor.raw_temperature
  icon: mdi:thermometer
  filters:
      - filter: lowpass
        time_constant: 10
        precision: 2

- platform: filter
  name: "Humidity"
  entity_id: sensor.raw_humidity
  icon: mdi:water-percent
  filters:
      - filter: lowpass
        time_constant: 10
        precision: 2
