# Weather prediction
- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - minutely_summary
    - precip_intensity
    - precip_probability
    - temperature
    - dew_point
    - wind_speed
    - cloud_cover
    - humidity
    - pressure
    - visibility

- platform: mqtt
  name: "Temperature"
  state_topic: "sonoff/dht11/tele/SENSOR"
  value_template: "{{ value_json['DHT11']['Temperature'] }}"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Humidity"
  state_topic: "sonoff/dht11/tele/SENSOR"
  value_template: "{{ value_json['DHT11']['Humidity'] }}"
  unit_of_measurement: "%"
